language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

env:
  # This is used to only capture the regular nightly test in allow_failures
  - REGULAR_TEST=true